name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Build and Test
        env:
          NSUnbufferedIO: "YES"
        run: |
          set -o pipefail
          xcodebuild \
            -project PostsApp.xcodeproj \
            -scheme PostsApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            clean test
